CREATE TABLE evento_alpr
(
    id_alpr    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    moto_id    BIGINT,
    placa_lida VARCHAR(255)                            NOT NULL,
    url_imagem VARCHAR(255),
    ts_alpr    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_eventoalpr PRIMARY KEY (id_alpr)
);

CREATE TABLE evento_wifi
(
    id_evento_wifi     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    moto_id            BIGINT,
    gateway_id_gateway BIGINT,
    rssits_evento      INTEGER,
    CONSTRAINT pk_eventowifi PRIMARY KEY (id_evento_wifi)
);

CREATE TABLE gateway
(
    id_gateway      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mac_address     VARCHAR(255)                            NOT NULL,
    descricao       VARCHAR(255),
    localid_zona_id BIGINT,
    CONSTRAINT pk_gateway PRIMARY KEY (id_gateway)
);

CREATE TABLE moto
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    modelo   VARCHAR(255),
    placa    VARCHAR(7),
    zona_id  BIGINT,
    status   SMALLINT,
    patio_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_moto PRIMARY KEY (id)
);

CREATE TABLE patio
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome             VARCHAR(255),
    quantidade_vagas INTEGER,
    metragem_zonaa   DOUBLE PRECISION,
    metragem_zonab   DOUBLE PRECISION,
    CONSTRAINT pk_patio PRIMARY KEY (id)
);

CREATE TABLE usuario (
    id_user  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_user VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL
);

CREATE TABLE zona
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo_zona VARCHAR(255)                            NOT NULL,
    metragem  DOUBLE PRECISION,
    nome      VARCHAR(255)                            NOT NULL,
    patio_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_zona PRIMARY KEY (id)
);

ALTER TABLE gateway
    ADD CONSTRAINT uc_gateway_mac_address UNIQUE (mac_address);

ALTER TABLE moto
    ADD CONSTRAINT uc_moto_placa UNIQUE (placa);

ALTER TABLE patio
    ADD CONSTRAINT uc_patio_nome UNIQUE (nome);

ALTER TABLE zona
    ADD CONSTRAINT uq_zona_patio_tipo UNIQUE (patio_id, tipo_zona);

ALTER TABLE evento_alpr
    ADD CONSTRAINT FK_EVENTOALPR_ON_MOTO FOREIGN KEY (moto_id) REFERENCES moto (id);

ALTER TABLE evento_wifi
    ADD CONSTRAINT FK_EVENTOWIFI_ON_GATEWAY_ID_GATEWAY FOREIGN KEY (gateway_id_gateway) REFERENCES gateway (id_gateway);

ALTER TABLE evento_wifi
    ADD CONSTRAINT FK_EVENTOWIFI_ON_MOTO FOREIGN KEY (moto_id) REFERENCES moto (id);

ALTER TABLE gateway
    ADD CONSTRAINT FK_GATEWAY_ON_LOCALID_ZONA FOREIGN KEY (localid_zona_id) REFERENCES zona (id);

ALTER TABLE moto
    ADD CONSTRAINT FK_MOTO_ON_ZONA FOREIGN KEY (zona_id) REFERENCES zona (id);

ALTER TABLE moto
    ADD CONSTRAINT FK_MOTO_PATIO FOREIGN KEY (patio_id) REFERENCES patio (id);

ALTER TABLE zona
    ADD CONSTRAINT FK_ZONA_PATIO FOREIGN KEY (patio_id) REFERENCES patio (id);